version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
     - FLASK_APP=grilmon/main.py
     - FLASK_DEBUG=1
    volumes:
     - .:/src
     - /run/systemd:/run/systemd
  builder:
    build:
        context: .
        dockerfile: Dockerfile.builder

